name: WonderEvents
version: ${project.version}
main: voiidstudios.wonderevents.WEBootstrap
api-version: '1.16'
authors:
  - Voiid Studios
description: WonderEvents Core
commands:
  wonderevents:
    description: WonderEvents administration command
    usage: /wonderevents <subcommand>
    aliases:
      - wonder
