Config:
  # Contribute to our statistics anonymously with FastStats. More information: https://faststats.dev/
  metrics: true

  # Settings for the automatic plugin updater
  auto_updater:
    # The plugin will attempt to auto-update when it finds a new version
    #!# YOU DOWNLOADED THIS PLUGIN FROM CURSEFORGE, Auto-update is NOT available on this build due to CurseForge's policies. Sorry! </3
    download: false
    # The plugin will send an update notification when it finds a new version if auto-update is disabled
    notify: true

    # How many seconds should the plugin wait before checking again for a new version?
    delay: 43200 # 12 hours

Messages:
  # Default language file located in messages/origins/<language>.yml
  language: en_US